#include <iostream>
#include <graphics.h>
#include <winbgim.h>
#include <cstring>

using namespace std;
#define MAX 50
#define APASAT 1
#define RELAXAT 2

void patrat(int x,int y,int lat)
{
    line(x-lat/2,y-lat/2,x-lat/2,y+lat/2);
    line(x-lat/2,y+lat/2,x+lat/2,y+lat/2);
    line(x+lat/2,y+lat/2,x+lat/2,y-lat/2);
    line(x+lat/2,y-lat/2,x-lat/2,y-lat/2);
}
void dreptunghi(int x,int y,int lat,int inalt)
{
    line(x-lat/2,y-inalt/2,x-lat/2,y+lat/2);
    line(x+lat/2,y+lat/2,x+lat/2,y-lat/2);
}

/*void fabuton(buton& b,int b.x1,int b.y1,int b.x2,int b.y2)
{
    if(stil==RELAXAT)
    {
        bar3d();
    }
    else
    {
        bar();
    }
}*/


void Trasare30careuri(int window1,char key,int c1)
{
    int i,j,nr,nr2,page,asciiValue,v[101];
    int result;

    page=0;
        /*setactivepage(page);
        setvisualpage(1 - page);
        cleardevice();*/

        rectangle(0,300,600,600);
        rectangle(0,100,600,150);
        rectangle(100,200,500,300);
        settextstyle(BOLD_FONT,HORIZ_DIR,4);//Fontu,Directia,Marimea
        outtextxy(150,60,"Introdu Functia");//Afisare text : "Introdu Functia"
        for(i=50;i<=600;i=i+50)
            line(i,100,i,150);
        for(i=25;i<=400;i=i+25)
            line(i+100,200,i+100,300);

        nr=1;
        for(i=0; i<=600; i=i+100)
        {
            if(i==300)
            {
                for(j=100; j<=600; j=j+100) //Trasam cele 18 triunghiuri
                {
                    line(j,i,j,600);
                    line(0,i+60*(j/100),600,i+60*(j/100));
                }
            }
            if(i>=300)
            {
                for(j=0; j<=500; j=j+100)
                {

                    if(nr==6)
                    {
                        settextstyle(BOLD_FONT,HORIZ_DIR,6);
                        outtextxy(j+5,i+5,"DEL");
                        outtextxy(j+30,i+5+60,"/");
                        outtextxy(j+30,i+5+120,"X");
                        outtextxy(j+30,i+5+180,"-");
                        outtextxy(j+30,i+5+240,"+");
                        nr++;
                    }
                    if(nr==5)
                    {
                        settextstyle(BOLD_FONT,HORIZ_DIR,6);
                        outtextxy(j+5,i+5,"EVL");
                        outtextxy(j+30,i+5+60,"9");
                        outtextxy(j+30,i+5+120,"6");
                        outtextxy(j+30,i+5+180,"3");
                        outtextxy(j+30,i+5+240,"=");
                        nr++;
                    }
                    if(nr==4)
                    {
                        settextstyle(BOLD_FONT,HORIZ_DIR,6);
                        outtextxy(j+30,i+5,")");
                        outtextxy(j+30,i+5+60,"8");
                        outtextxy(j+30,i+5+120,"5");
                        outtextxy(j+30,i+5+180,"2");
                        outtextxy(j+30,i+5+240,".");
                        nr++;
                    }
                    if(nr==3)
                    {
                        settextstyle(BOLD_FONT,HORIZ_DIR,6);
                        outtextxy(j+30,i+5,"(");
                        outtextxy(j+30,i+5+60,"7");
                        outtextxy(j+30,i+5+120,"4");
                        outtextxy(j+30,i+5+180,"1");
                        outtextxy(j+30,i+5+240,"0");
                        nr++;
                    }
                    if(nr==2)
                    {
                        settextstyle(BOLD_FONT,HORIZ_DIR,6);
                        outtextxy(j+30,i+5,">");
                        outtextxy(j+30,i+5+60,"^");
                        outtextxy(j+5,i+5+120,"RAD");
                        outtextxy(j+5,i+5+180,"exp");
                        outtextxy(j+30,i+5+240,"e");
                        nr++;
                    }
                    if(nr==1)
                    {
                        settextstyle(BOLD_FONT,HORIZ_DIR,6);
                        outtextxy(30,i+5,"<");
                        outtextxy(5,i+5+60,"sin");
                        outtextxy(5,i+5+120,"cos");
                        outtextxy(20,i+5+180,"ln");
                        outtextxy(20,i+5+240,"PI");
                        nr++;
                    }
                }
            }
        }
        switch(key)
        {
            case 60:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"<");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"<");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"<");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"<");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"<");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"<");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"<");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"<");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"<");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"<");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"<");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"<");
                }
                c1++;
                break;
            }
            case 62:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,">");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,">");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,">");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,">");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,">");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,">");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,">");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,">");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,">");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,">");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,">");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,">");
                }
                c1++;
                break;
            }
            case 40:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"(");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"(");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"(");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"(");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"(");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"(");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"(");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"(");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"(");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"(");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"(");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"(");
                }
                c1++;
                break;
            }
            case 41:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,")");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,")");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,")");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,")");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,")");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,")");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,")");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,")");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,")");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,")");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,")");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,")");
                }
                c1++;
                break;
            }
            case 94:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"^");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"^");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"^");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"^");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"^");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"^");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"^");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"^");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"^");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"^");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"^");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"^");
                }
                c1++;
                break;
            }
            case 101:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"e");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"e");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"e");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"e");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"e");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"e");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"e");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"e");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"e");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"e");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"e");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"e");
                }
                c1++;
                break;
            }
            case 46:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,".");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,".");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,".");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,".");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,".");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,".");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,".");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,".");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,".");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,".");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,".");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,".");
                }
                c1++;
                break;
            }
            case 61:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"=");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"=");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"=");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"=");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"=");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"=");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"=");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"=");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"=");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"=");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"=");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"=");
                }
                c1++;
                break;
            }
            case 47:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"/");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"/");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"/");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"/");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"/");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"/");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"/");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"/");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"/");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"/");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"/");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"/");
                }
                c1++;
                break;
            }
            case 88:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"X");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"X");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"X");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"X");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"X");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"X");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"X");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"X");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"X");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"X");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"X");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"X");
                }
                c1++;
                break;
            }
            case 43:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"+");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"+");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"+");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"+");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"+");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"+");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"+");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"+");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"+");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"+");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"+");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"+");
                }
                c1++;
                break;
            }
            case 45:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"-");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"-");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"-");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"-");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"-");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"-");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"-");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"-");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"-");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"-");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"-");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"-");
                }
                c1++;
                break;
            }
            case 48:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"0");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"0");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"0");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"0");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"0");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"0");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"0");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"0");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"0");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"0");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"0");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"0");
                }
                c1++;
                break;
            }
            case 49:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"1");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"1");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"1");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"1");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"1");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"1");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"1");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"1");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"1");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"1");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"1");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"1");
                }
                c1++;
                break;
            }
            case 50:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"2");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"2");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"2");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"2");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"2");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"2");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"2");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"2");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"2");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"2");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"2");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"2");
                }
                c1++;
                break;
            }
            case 51:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"3");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"3");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"3");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"3");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"3");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"3");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"3");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"3");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"3");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"3");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"3");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"3");
                }
                c1++;
                break;
            }
            case 52:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"4");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"4");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"4");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"4");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"4");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"4");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"4");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"4");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"4");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"4");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"4");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"4");
                }
                c1++;
                break;
            }
            case 53:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"5");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"5");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"5");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"5");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"5");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"5");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"5");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"5");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"5");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"5");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"5");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"5");
                }
                c1++;
                break;
            }
            case 54:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"6");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"6");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"6");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"6");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"6");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"6");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"6");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"6");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"6");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"6");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"6");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"6");
                }
                c1++;
                break;
            }
            case 55:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"7");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"7");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"7");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"7");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"7");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"7");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"7");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"7");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"7");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"7");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"7");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"7");
                }
                c1++;
                break;
            }
            case 56:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"8");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"8");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"8");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"8");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"8");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"8");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"8");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"8");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"8");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"8");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"8");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"8");
                }
                c1++;
                break;
            }
            case 57:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*0,105,"9");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*1,105,"9");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*2,105,"9");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*3,105,"9");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*4,105,"9");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*5,105,"9");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*6,105,"9");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*7,105,"9");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*8,105,"9");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*9,105,"9");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*10,105,"9");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,5);
                    outtextxy(560-50*11,105,"9");
                }
                c1++;
                break;
            }
            case 108:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*0,110,"ln");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*1,110,"ln");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*2,110,"ln");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*3,110,"ln");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*4,110,"ln");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*5,110,"ln");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*6,110,"ln");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*7,110,"ln");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*8,110,"ln");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*9,110,"ln");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*10,110,"ln");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*11,110,"ln");
                }
                c1++;
                break;
            }
            case 80:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*0,110,"PI");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*1,110,"PI");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*2,110,"PI");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*3,110,"PI");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*4,110,"PI");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*5,110,"PI");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*6,110,"PI");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*7,110,"PI");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*8,110,"PI");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*9,110,"PI");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*10,110,"PI");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,4);
                    outtextxy(555-50*11,110,"PI");
                }
                c1++;
                break;
            }
            case 82:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*0,115,"RAD");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*1,115,"RAD");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*2,115,"RAD");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*3,115,"RAD");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*4,115,"RAD");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*5,115,"RAD");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*6,115,"RAD");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*7,115,"RAD");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*8,115,"RAD");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*9,115,"RAD");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*10,115,"RAD");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*11,115,"RAD");
                }
                c1++;
                break;
            }
            case 115:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*0,115,"sin");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*1,115,"sin");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*2,115,"sin");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*3,115,"sin");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*4,115,"sin");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*5,115,"sin");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*6,115,"sin");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*7,115,"sin");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*8,115,"sin");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*9,115,"sin");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*10,115,"sin");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*11,115,"sin");
                }
                c1++;
                break;
            }
            case 99:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*0,115,"cos");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*1,115,"cos");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*2,115,"cos");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*3,115,"cos");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*4,115,"cos");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*5,115,"cos");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*6,115,"cos");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*7,115,"cos");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*8,115,"cos");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*9,115,"cos");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*10,115,"cos");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*11,115,"cos");
                }
                c1++;
                break;
            }
            case 69:
            {
                if(c1==11)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*0,115,"Exp");
                }
                if(c1==10)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*1,115,"Exp");
                }
                if(c1==9)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*2,115,"Exp");
                }
                if(c1==8)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*3,115,"Exp");
                }
                if(c1==7)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*4,115,"Exp");
                }
                if(c1==6)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*5,115,"Exp");
                }
                if(c1==5)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*6,115,"Exp");
                }
                if(c1==4)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*7,115,"Exp");
                }
                if(c1==3)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*8,115,"Exp");
                }
                if(c1==2)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*9,115,"Exp");
                }
                if(c1==1)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*10,115,"Exp");
                }
                if(c1==0)
                {
                    settextstyle(BOLD_FONT,HORIZ_DIR,3);
                    outtextxy(555-50*11,115,"Exp");
                }
                c1++;
                break;
            }
            default:
                break;
        }
        //page=1-page;
}

void cinTastatura(int window1,char c[101])
{
    int i,nr=0;
    for(i=0;i<strlen(c);i++)
    {
        if(c[i]!='n' && c[i]!='I' && c[i]!='A' && c[i]!='D' && c[i]!='i' && c[i]!='s' && c[i]!='o' && c[i]!='x'  && c[i]!='p')
            Trasare30careuri(window1,c[i],nr);
        else
            nr--;
        nr++;
    }
}
